# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4a26e5b1-eb6a-4515-89a6-03149685d61c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FE22-414B";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/84333808-d6dc-49a7-9391-6c68ba708e88";
      fsType = "ext4";
    };

  fileSystems."/media/share" =
    { device = "/dev/disk/by-label/storage";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/63cdf8a9-a2aa-45cb-bbf9-03380729bcbb"; }
    ];

  nix.settings.max-jobs = lib.mkDefault 6;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
