# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot = {
    initrd = {
      availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
    };
    kernelModules = [ "kvm-intel" "fuse" "coretemp" ]; # ++ ["cpufreq_powersafe" "cpufreq_performance"];
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6f172a81-461f-48bd-9074-085e68a644ce";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/25cb015b-7fe5-496a-b6d8-434a254b7310";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5A9A-132C";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/32cad05a-7281-4588-9bf9-23313b8068e4"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  # in configuraion
  # powerManagement.cpuFreqGovernor = "ondemand"; # tlp does it
}
