simplified_ui: false
pane_frames: false
# default_shell: fish

# default_mode: locked
keybinds:
    locked:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'f',]
    scroll:
        - action: [PageScrollDown,]
          key: [Ctrl: 'f', PageDown,]
        - action: [PageScrollUp,]
          key: [Ctrl: 'b', PageUp,]
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'f',]
    normal:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'f',]    
    pane:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'f',]
    tab:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'f',]
    resize:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'f',]
    move:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'f',]
    search:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'f',]
    session:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'f',]
    renametab:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'f',]
    renamepane:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'f',]
