simplified_ui: false
pane_frames: false
mouse_mode: false # disable in nested mode to copy things natively
# default_shell: fish

# default_mode: locked
keybinds:
    locked:
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'l',]
    scroll:
        - action: [PageScrollDown,]
          key: [Ctrl: 'l', PageDown,]
        - action: [PageScrollUp,]
          key: [Ctrl: 'b', PageUp,]
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'l',]
    normal:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'l',]    
    pane:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'l',]
    tab:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'l',]
    resize:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'l',]
    move:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'l',]
    search:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'l',]
    session:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'l',]
    renametab:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'l',]
    renamepane:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'l',]
