simplified_ui: false
pane_frames: false
default_shell: fish

# default_mode: locked
keybinds:
    scroll:
        - action: [PageScrollDown,]
          key: [Ctrl: 'f', PageDown,]
        - action: [PageScrollUp,]
          key: [Ctrl: 'b', PageUp,]
